# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_account_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_content', models.CharField(max_length=300)),
                ('user_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_content', models.CharField(max_length=300)),
                ('admin_pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='accounts.Account')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.Account')),
            ],
        ),
    ]
