# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='admin',
        ),
    ]
