# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20160713_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='admin_content',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
