# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findpassword',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
