# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='readed',
            field=models.BooleanField(default=False),
        ),
    ]
