# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('pwd', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=11)),
                ('phone_verified', models.BooleanField(default=False)),
                ('reg_time', models.DateTimeField(null=True)),
                ('last_ip', models.GenericIPAddressField(null=True)),
                ('campus', models.CharField(choices=[('NQ', '南区'), ('BQ', '北区'), ('NL', '南岭'), ('NH', '南湖'), ('HP', '和平'), ('CY', '朝阳'), ('XM', '新民')], default='NQ', max_length=2)),
            ],
        ),
    ]
