# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='campus',
            field=models.CharField(choices=[('NQ', '南区'), ('NL', '南岭'), ('NH', '南湖'), ('HP', '和平'), ('CY', '朝阳'), ('XM', '新民')], default='NQ', max_length=2),
        ),
    ]
