# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160319_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
