# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160319_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
