# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160706_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
