# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='qq',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
