# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='account',
            name='qq',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
