# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160714_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='college',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='entry_year',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
