# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20160714_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='college',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='entry_year',
            field=models.CharField(blank=True, default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
