# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160319_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 19, 3, 0, 38, 97125, tzinfo=utc)),
        ),
    ]
