# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='campus',
            field=models.CharField(choices=[('NQ', '南区'), ('BQ', '北区'), ('HP', '和平'), ('CY', '朝阳'), ('XM', '新民'), ('NH', '南湖'), ('NL', '南岭')], default='NQ', max_length=2),
        ),
    ]
