# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imgs',
        ),
        migrations.AddField(
            model_name='product',
            name='big_imgs',
            field=models.ImageField(default=None, upload_to='big'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_imgs',
            field=models.ImageField(default=None, upload_to='small'),
            preserve_default=False,
        ),
    ]
