# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20160623_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(choices=[('1', '出售'), ('2', '交换'), ('3', '求购')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='campus',
            field=models.CharField(choices=[('NQ', '南区'), ('HP', '和平'), ('CY', '朝阳'), ('XM', '新民'), ('NH', '南湖'), ('NL', '南岭')], default='NQ', max_length=2),
        ),
    ]
