# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160710_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('on_sell', '在售中'), ('sold_out', '已售出')], default='on_sell', max_length=10),
        ),
    ]
