# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='small_img',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
