# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20160712_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='big_imgs',
            field=models.CharField(default='big/default.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='small_imgs',
            field=models.CharField(default='small/default.png', max_length=500),
        ),
    ]
