# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20160712_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='product',
            name='qq',
            field=models.CharField(default='', max_length=15),
        ),
    ]
