# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20160713_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qq',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
