# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20160713_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='qq',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
